### ISSUE TITLE
Getting started REST endpoint return empty JSON bodies

### ISSUE THREAD

**Issue by chamika** [agoncal/agoncal-fascicle-quarkus#24]
I started building `agoncal-fascicle-quarkus/getting-started` project. The `quarkus:dev` and `getting-started-1.0-SNAPSHOT-runner.jar` works perfectly fine and getting following response for `http://localhost:8080/artists`

```
[
  {
    "first_name": "John",
    "last_name": "Lennon"
  },
  {
    "first_name": "Paul",
    "last_name": "McCartney"
  },
  {
    "first_name": "George",
    "last_name": "Harrison"
  },
  {
    "first_name": "Ringo",
    "last_name": "Starr"
  }
]
```

However, when I build the native image and run that JSON bodies are not returning correctly.
Steps:
1. Build native image using ` ./mvnw package -Pnative`
2. Access URL using `curl http://localhost:8080/artists | jq`

Actual response:
```
[
  {},
  {},
  {},
  {}
]
```

Expected response:

```
[
  {
    "first_name": "John",
    "last_name": "Lennon"
  },
  {
    "first_name": "Paul",
    "last_name": "McCartney"
  },
  {
    "first_name": "George",
    "last_name": "Harrison"
  },
  {
    "first_name": "Ringo",
    "last_name": "Starr"
  }
]
```

Environment details:
Ubuntu 20.10 - Kernal 5.8.0-41-generic

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

**Comment by bouhinho** [comment]
got the same issue yesterday, with the same pc config.

**Comment by khekrn** [comment]
Need to add `@RegisterForReflection` in Artist.java. This is because we are returning raw Response type in ArtistResource.

**Comment by chamika** [comment]
@khekrn Thanks. Adding `@RegisterForReflection` worked. Hence closing the issue.
